<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Blockcore Features Dns</Description>
    <AssemblyTitle>Blockcore.Features.Dns</AssemblyTitle>
    <AssemblyName>Blockcore.Features.Dns</AssemblyName>
    <PackageId>Blockcore.Features.Dns</PackageId>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DNS" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="10.0.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Blockcore\Blockcore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1705;IDE0008;</NoWarn>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

</Project>
